version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '5000:5000'
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local